name: Mark and close stale issues

on:
  schedule:
  - cron: "30 1 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: '현 이슈는 7일 이상 활동이 없어서 stale 상태입니다. 3일 후에 자동으로 닫힐 예정입니다. 변경을 원한다면 댓글을 달거나 stale 레이블을 제거하세요'
        days-before-stale: 7
        days-before-close: 3